### ISSUE TITLE
Concurrent Modification Exception on CLIENT DISCONNECT

### ISSUE THREAD

**Issue by jasonkatz** [jgreens/set#17]
There are instances of the system where disconnected a client throws a Concurrent Modification Exception on CLIENT DISCONNECT. This seems to be happening in the games HashMap in Lobby.java. This issue occurred when dealing with game deletion with multiple users in the lobby (exact circumstances unclear).

**Comment by akshaynavada** [comment]
i think the problem is with removing elements from arraylist, while iterating through list, apparently u cant do that, ill try to fix it:
http://stackoverflow.com/questions/18448671/how-to-avoid-concurrentmodificationexception-while-removing-elements-from-arr
